$(function(){
            $(".tdata1").click(function(){
               $(".tpaneli1").slideToggle("slow")
            });
        });
        $(function(){
                    $(".tdata2").click(function(){
                       $(".tpaneli2").slideToggle("slow")
                    });
                });
                $(function(){
                            $(".tdata3").click(function(){
                               $(".tpaneli3").slideToggle("slow")
                            });
                        });
                        $(function(){
                                    $(".tdata4").click(function(){
                                       $(".tpaneli4").slideToggle("slow")
                                    });
                                });
